name = "PANDA"
uuid = "57a71ab2-c1ee-420a-94e0-f42fd769768c"
authors = ["Helene Morlon", "Ignacio Quintero", "Odile Maliet"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
